{% set name = "trompeloeil" %}
{% set version = "44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rollbear/trompeloeil/archive/v{{ version }}.tar.gz
  sha256: 004877db6ba22f24c7867e112e081eeb68858122f55ebe7c7dd9d8d9e3b46c88

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - ninja

test:
  requires:
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  files:
    - test

  commands:
    - cd test
    - cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ./program  # [unix]
    - program.exe  # [win]

about:
  home: https://github.com/rollbear/trompeloeil
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: Header only C++14 mocking framework

extra:
  recipe-maintainers:
    - apmorton
